name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: FluentUI.sln
      Project_Name: FluentUI.Design\FluentUI.Design.csproj
      Source_Output: ${{ github.workspace }}\Output\Source\
      Build_Output: ${{ github.workspace }}\Output\FluentUI\
      Source_Zip: ${{ github.workspace }}\Output\Source.zip
      Build_Zip: ${{ github.workspace }}\Output\FluentUI.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Copy the source code to the output directory
    - name: Copy source code
      run: cp -r $env:GITHUB_WORKSPACE\* $env:Source_Output

    # Zip the source code
    - name: Zip source code
      run: 7z a -tzip $env:Source_Zip $env:Source_Output

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Build the application
    - name: Build the application
      run: msbuild $env:Project_Name /p:Configuration=$env:Configuration /p:Platform="Any CPU" /p:OutputPath=$env:Build_Output
      env:
        Configuration: ${{ matrix.configuration }}

    # Zip the build output
    - name: Zip the build output
      run: 7z a -tzip $env:Zip_Output $env:Build_Output

    # Release the build output
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        body: ${{ github.ref }}
        draft: true
        files: |
          ./Output/*.zip
